var network = {
    version: "0.0.1",
    files: [
        "alpha.png",
        "alpha_gradient.png",
        "color.js",
        "color_background.png",
        "color_slider.png",
        "draw.js",
        "index.html",
        "launch.js",
        "launcher.css",
        "launcher.html",
        "launcher.js",
        "launcherBackground.png",
        "main.js",
        "package-lock.json",
        "package.json",
        "render.js",
        "renderer.js",
        "save.js",
        "styles.css",
        "window.css",
        "window.js",
    ],
};